Gh12 ut control building issues from testing suite
rdkcentral/ut-control pull request #13
Opened 2024-06-20 08:42 UTC by kanjoe24

2024-06-20 11:20 UTC, Ulrond requested changes
minor changes.

2024-06-20 11:20 UTC, Ulrond commented on include/ut_kvp.h
> +#include <ut_log.h>
remove this.

2024-06-20 11:20 UTC, Ulrond commented on src/ut_control_plane.c
> +#define UT_CONTROL_PLANE_ERROR(f_, ...) UT_LOG_ERROR((f_), ##__VA_ARGS__)
include <ut_log.h> - here.

2024-06-20 11:20 UTC, Ulrond commented on src/ut_kvp.c
>  #include <ut_kvp.h>
`#include <ut_log.h>` - required

2024-06-20 16:47 UTC, kanjoe24 commented on tests/Makefile
> +LIBWEBSOCKET_LIB_DIR = $(ROOT_DIR)/../framework/libwebsockets-4.3.3/build/lib
Added this as hack as of now, will remove later

2024-06-21 09:43 UTC, Ulrond commented on include/ut_kvp.h
Add void* into the callback

```c
typedef void (*ut_control_callback_t)( char *key, ut_kvp_instance_t *instance, void *userData );
...
ut_control_plane_status_t UT_ControlPlane_RegisterCallbackOnMessage(
                                                                    ut_controlPlane_instance_t *pInstance,
                                                                    char *key,
                                                                    ut_control_callback_t callbackFunction
                                                                    void *userData );
```

2024-06-21 09:46 UTC, Ulrond commented on include/ut_kvp.h
remove `void ut_kvp_print( ut_kvp_instance_t *pInstance );` and replace with `uint8_t *ut_kvp_getData( ut_kvp_instance_t *pInstance, uint32_t *pReturnedLength );`

- Upgrading the tests as required still to print but the print will be external and you will call getData instead.

Ensure that you state that the `@note: caller is responsible for freeing the memory` in the doxygen comments.

2024-06-21 16:20 UTC, Ulrond approved these changes
looks good

2024-06-21 16:22 UTC, merged