gh51 : Updating the functions to reflect accurate info
rdkcentral/ut-control pull request #54
Opened 2024-10-21 14:14 UTC by kanjoe24

2024-10-23 09:11 UTC, kanjoe24 commented
Release test script results:

```
 ./release-test-script-ut-control.sh -t feature/gh51-fix-relative-path
==========================================================
RESULTS for ubuntu 
On the branch feature/gh51-fix-relative-path. PASS
build/linux/curl/lib/libcurl.a exists. PASS
Openssl static lib does not exist. PASS 
CMake host binary does not exist. PASS 
==========================================================
==========================================================
RESULTS for VM-SYNC 
On the branch feature/gh51-fix-relative-path. PASS
build/linux/curl/lib/libcurl.a exists. PASS
build/linux/openssl/lib/libssl.a exists. PASS 
host-tools/CMake-3.30.0/build/bin/cmake exists. PASS 
==========================================================
==========================================================
RESULTS for dunfell_arm 
On the branch feature/gh51-fix-relative-path. PASS
build/arm/curl/lib/libcurl.a exists. PASS
build/arm/openssl/lib/libssl.a exists. PASS 
CMake host binary does not exist. PASS 
==========================================================
==========================================================
RESULTS for dunfell_linux 
On the branch feature/gh51-fix-relative-path. PASS
build/linux/curl/lib/libcurl.a exists. PASS
Openssl static lib does not exist. PASS 
CMake host binary does not exist. PASS 
==========================================================
==========================================================
RESULTS for kirkstone_arm 
On the branch feature/gh51-fix-relative-path. PASS
build/arm/curl/lib/libcurl.a exists. PASS
build/arm/openssl/lib/libssl.a exists. PASS 
CMake host binary does not exist. PASS 
==========================================================
==========================================================
RESULTS for kirkstone_linux 
On the branch feature/gh51-fix-relative-path. PASS
build/linux/curl/lib/libcurl.a exists. PASS
Openssl static lib does not exist. PASS 
CMake host binary does not exist. PASS 
==========================================================

```

2024-10-24 15:11 UTC, Ulrond requested changes
ah sorry forgot to push this one out.

2024-10-24 15:36 UTC, kanjoe24 commented on src/ut_kvp.c
> +        UT_LOG_ERROR("node not found for key = %s : UT_KVP_STATUS_KEY_NOT_FOUND", pszKey);
sorry, why will that not be an error. We are returning false if don't find the node for the said key. I didn't understand...

2024-10-28 10:27 UTC, kanjoe24 commented on src/ut_kvp.c
> +        //UT_LOG_DEBUG("node not found for key = [%s] : UT_KVP_STATUS_KEY_NOT_FOUND", pszKey);
Upgrade logging module to have levels of logging and also instances

2024-10-28 10:32 UTC, Ulrond approved these changes
looks good

2024-10-28 10:38 UTC, kanjoe24 commented on src/ut_kvp.c
> +        UT_LOG_ERROR("node not found for key = %s : UT_KVP_STATUS_KEY_NOT_FOUND", pszKey);
done

2024-10-28 11:14 UTC, kanjoe24 commented
test Script results:
```
./release-test-script-ut-control.sh -t feature/gh51-fix-relative-path
==========================================================
RESULTS for kirkstone_arm 
On the branch feature/gh51-fix-relative-path. PASS
build/arm/curl/lib/libcurl.a exists. PASS
build/arm/openssl/lib/libssl.a exists. PASS 
CMake host binary does not exist. PASS 
==========================================================
==========================================================
RESULTS for ubuntu 
On the branch feature/gh51-fix-relative-path. PASS
build/linux/curl/lib/libcurl.a exists. PASS
Openssl static lib does not exist. PASS 
CMake host binary does not exist. PASS 
==========================================================
==========================================================
RESULTS for VM-SYNC 
On the branch feature/gh51-fix-relative-path. PASS
build/linux/curl/lib/libcurl.a exists. PASS
build/linux/openssl/lib/libssl.a exists. PASS 
host-tools/CMake-3.30.0/build/bin/cmake exists. PASS 
==========================================================
==========================================================
RESULTS for dunfell_arm 
On the branch feature/gh51-fix-relative-path. PASS
build/arm/curl/lib/libcurl.a exists. PASS
build/arm/openssl/lib/libssl.a exists. PASS 
CMake host binary does not exist. PASS 
==========================================================
==========================================================
RESULTS for dunfell_linux 
On the branch feature/gh51-fix-relative-path. PASS
build/linux/curl/lib/libcurl.a exists. PASS
Openssl static lib does not exist. PASS 
CMake host binary does not exist. PASS 
==========================================================
==========================================================
RESULTS for kirkstone_arm 
On the branch feature/gh51-fix-relative-path. PASS
build/arm/curl/lib/libcurl.a exists. PASS
build/arm/openssl/lib/libssl.a exists. PASS 
CMake host binary does not exist. PASS 
==========================================================
==========================================================
RESULTS for kirkstone_linux 
On the branch feature/gh51-fix-relative-path. PASS
build/linux/curl/lib/libcurl.a exists. PASS
Openssl static lib does not exist. PASS 
CMake host binary does not exist. PASS 
==========================================================
```

2024-10-28 11:15 UTC, merged